import { ApiProperty } from '@nestjs/swagger';
import { IsString, Matches } from 'class-validator';

export class UserExpoPushTokenUpdateDto {
  @ApiProperty({
    example: 'ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]',
    description: 'Expo push token generated by the mobile app',
  })
  @IsString()
  @Matches(/^ExponentPushToken\[.+\]$/, {
    message:
      'expoPushToken must be a valid Expo push token (e.g. ExponentPushToken[xxx])',
  })
  expoPushToken: string;
}
