ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "level" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "favoriteCourt" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "preferredTimeSlots" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "expoPushToken" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifyPush" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifySms" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifyEmail" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0;
